CIDADES_POR_ESTADO = {
     "Acre": [
        "Rio Branco", "Cruzeiro do Sul", "Sena Madureira", "Tarauacá",
        "Feijó", "Brasileia", "Epitaciolândia", "Senador Guiomard",
        "Plácido de Castro", "Xapuri", "Mâncio Lima", "Marechal Thaumaturgo",
        "Porto Walter", "Santa Rosa do Purus", "Jordão", "Porto Acre",
        "Bujari", "Capixaba", "Acrelândia", "Rodrigues Alves",
        "Assis Brasil", "Manoel Urbano", "Lokito", "Porto Walter",
        "Guajará", "Ipixuna"
    ],
    "Alagoas": [
        "Maceió", "Arapiraca", "Palmeira dos Índios", "Rio Largo",
        "Penedo", "União dos Palmares", "São Miguel dos Campos", "Santana do Ipanema",
        "Delmiro Gouveia", "Coruripe", "Marechal Deodoro", "Campo Alegre",
        "Murici", "Joaquim Gomes", "Matriz de Camaragibe", "Porto Calvo",
        "Pão de Açúcar", "Piranhas", "Traipu", "Girau do Ponciano",
        "São Luís do Quitunde", "Flexeiras", "Branquinha", "Messias",
        "Atalaia", "Anadia", "Boca da Mata", "Roteiro",
        "Jequiá da Praia", "Paripueira", "Barra de Santo Antônio", "Porto de Pedras",
        "Japaratinga", "Maragogi", "Passo de Camaragibe", "São José da Tapera",
        "Batalha", "Major Isidoro", "Senador Rui Palmeira", "Água Branca",
        "Canapi", "Inhapi", "Olho d'Água do Casado", "Poço das Trincheiras",
        "Monteirópolis", "Ouro Branco", "Carneiros", "Dois Riachos",
        "Olivença", "Igaci", "Limoeiro de Anadia", "Taquarana",
        "Craíbas", "Lagoa da Canoa", "Feira Grande", "Belém",
        "São Sebastião", "Teotônio Vilela", "Junqueiro", "Campo Grande",
        "Viçosa", "Quebrangulo", "Mar Vermelho", "Minador do Negrão",
        "Cacimbinhas", "Jacaré dos Homens", "Palestina", "Coité do Nóia",
        "Igreja Nova", "Propriá", "Piaçabuçu", "Feliz Deserto",
        "São Brás", "Jundiá", "Colônia Leopoldina", "Novo Lino",
        "Chã Preta", "Paulo Jacinto", "Cajueiro", "Satuba",
        "Coqueiro Seco", "Santa Luzia do Norte", "Pilar", "São Miguel dos Milagres",
        "Barra de São Miguel", "Campestre", "Tanque d'Arca", "Inhapi",
        "Água Branca", "Pariconha", "Mata Grande", "Maravilha",
        "Santana do Mundaú", "Ibateguara", "União dos Palmares", "Branquinha",
        "Murici", "Colônia Leopoldina", "Joaquim Gomes", "Pindoba",
        "Lagoa Grande", "Tanque d'Arca", "Girau do Ponciano", "Arapiraca",
    ],
    "Amapá": [
        "Macapá", "Santana", "Laranjal do Jari", "Oiapoque",
        "Mazagão", "Porto Grande", "Tartarugalzinho", "Pedra Branca do Amapari",
        "Calçoene", "Amapá", "Cutias", "Ferreira Gomes",
        "Itaubal", "Pracuúba", "Serra do Navio", "Vitória do Jari",
    ],
    "Amazonas": [
        "Manaus", "Parintins", "Itacoatiara", "Manacapuru",
        "Coari", "Tefé", "Tabatinga", "Maués",
        "Humaitá", "Uruará", "Manicoré", "Lábrea",
        "Borba", "Novo Aripuanã", "Fonte Boa", "Juruá",
        "Jutaí", "Eirunepé", "Carauari", "Envira",
        "Guajará", "Ipixuna", "Itamarati", "Tapauá",
        "Beruri", "Anori", "Anamã", "Caapiranga",
        "Manaquiri", "Careiro", "Careiro da Várzea", "Iranduba",
        "Novo Airão", "Presidente Figueiredo", "Rio Preto da Eva", "Autazes",
        "Itapiranga", "Silves", "Urucurituba", "Boa Vista do Ramos",
        "Barreirinha", "Nhamundá", "Urucará", "São Sebastião do Uatumã",
        "Itamarati", "Pauini", "Boca do Acre", "Canutama",
        "Tapauá", "Codajás", "Coari", "Tefé",
        "Alvarães", "Uarini", "Maraã", "Japurá",
        "Tonantins", "Santo Antônio do Içá", "Amaturá", "São Paulo de Olivença",
        "Benjamin Constant", "Atalaia do Norte", "Jutaí", "Juruá",
        "Barcelos", "Santa Isabel do Rio Negro", "São Gabriel da Cachoeira", "Japurá",
        "Roraima", "Novo Airão", "Caroebe", "Caracaraí",
    ],
    "Bahia": [
        "Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari",
        "Itabuna", "Juazeiro", "Lauro de Freitas", "Ilhéus",
        "Jequié", "Teixeira de Freitas", "Alagoinhas", "Barreiras",
        "Porto Seguro", "Simões Filho", "Paulo Afonso", "Eunápolis",
        "Santo Antônio de Jesus", "Valença", "Luís Eduardo Magalhães", "Candeias",
        "Jacobina", "Serrinha", "Senhor do Bonfim", "Guanambi",
        "Brumado", "Itapetinga", "Cruz das Almas", "Tucano",
        "Euclides da Cunha", "Ribeira do Pombal", "Irecê", "Ipiaú",
        "Itaberaba", "Santo Amaro", "Conceição do Coité", "Dias d'Ávila",
        "Madre de Deus", "São Francisco do Conde", "Mata de São João", "Entre Rios",
        "Esplanada", "Conde", "Pojuca", "Catu",
        "Inhambupe", "Acajutiba", "Olindina", "Aramari",
        "Cardeal da Silva", "Jandaíra", "Sátiro Dias", "Biritinga",
        "Cipó", "Ribeira do Amparo", "Água Fria", "Pedrão",
        "Antônio Cardoso", "Coração de Maria", "Tanquinho", "Candeal",
        "Ichu", "Anguera", "Santa Bárbara", "Teodoro Sampaio",
        "Itapicuru", "Nova Soure", "Adustina", "Banzaê",
        "Fátima", "Cícero Dantas", "Jeremoabo", "Pedro Alexandre",
        "Coronel João Sá", "Antas", "Glória", "Chorrochó",
        "Rodelas", "Curaçá", "Uauá", "Monte Santo",
        "Canudos", "Queimadas", "Quijingue", "Nordestina",
        "Santaluz", "Valente", "Araci", "Barrocas",
        "Itiúba", "Campo Formoso", "Pindobaçu", "Filadélfia",
        "Antônio Gonçalves", "Ponto Novo", "Mairi", "Capim Grosso",
        "Gavião", "Várzea da Roça", "Tapiramutá", "Ipirá",
        "Baixa Grande", "Mundo Novo", "Serrolândia", "Caém",
        "Saúde", "Ourolândia", "Morro do Chapéu", "Várzea Nova",
        "Umburanas", "Lagoa Grande", "Jaguarari", "Caldeirão Grande",
        "Miguel Calmon", "Lençóis", "Palmeiras", "Mucugê",
        "Andaraí", "Nova Redenção", "Ibicoara", "Ituaçu",
        "Contendas do Sincorá", "Livramento de Nossa Senhora", "Dom Basílio", "Tanhaçu",
        "Aracatu", "Ibiassucê", "Caetité", "Lagoa Real",
        "Piatã", "Ibipeba", "Barra do Mendes", "Canarana",
        "América Dourada", "João Dourado", "Ipupiara", "Barro Alto",
        "Ibiquera", "Lajedinho", "Ruy Barbosa", "Marcionílio Souza",
        "Nova Itarana", "Planaltino", "Maracás", "Jaguaquara",
        "Amargosa", "Brejões", "Ubaíra", "Itaquara",
        "Laje", "Mutuípe", "Jiquiriçá", "Santa Inês",
        "Irajuba", "Milagres", "Itamari", "Gongogi",
        "Aurelino Leal", "Ubaitaba", "Camamu", "Igrapiúna",
        "Ituberá", "Nilo Peçanha", "Taperoá", "Cairu",
        "Maraú", "Itacaré", "Uruçuca", "Almadina",
        "Barro Preto", "Coaraci", "Ibicaraí", "Itaju do Colônia",
        "Itapé", "Firmino Alves", "Floresta Azul", "Santa Cruz da Vitória",
        "Pau Brasil", "Caatiba", "Itambé", "Ribeirão do Largo",
        "Macarani", "Maiquinique", "Itarantim", "Potiraguá",
        "Belo Campo", "Tremedal", "Piripá", "Licínio de Almeida",
        "Mortugaba", "Cordeiros", "Condeúba", "Jacaraci",
        "Urandi", "Candiba", "Palmas de Monte Alto", "Igaporã",
        "Malhada", "Carinhanha", "Feira da Mata", "Cocos",
        "Correntina", "Jaborandi", "Coribe", "Serra Dourada",
        "Santana", "Brejolândia", "Tabocas do Brejo Velho", "Wanderley",
        "Bom Jesus da Lapa", "Paratinga", "Ibotirama", "Morpará",
        "Buritirama", "Cotegipe", "Angical", "Baianópolis",
        "Cristópolis", "São Desidério", "Formosa do Rio Preto", "Riachão das Neves",
        "Mansidão", "Xique-Xique", "Barra", "Pilão Arcado",
        "Remanso", "Sento Sé", "Campo Alegre de Lourdes", "Sobradinho",
        "Casa Nova", "Macururé", "Santa Brígida", "Abaré",
        "Canápolis", "Oliveira dos Brejinhos", "Brotas de Macaúbas", "Boninal",
        "Iraquara", "Seabra", "Wagner", "Utinga",
        "Mulungu do Morro", "Souto Soares", "Gentio do Ouro", "Ibitita",
        "Uibaí", "Central", "Jussara", "Presidente Dutra",
        "São Gabriel", "Lapão", "Ibititá", "Cafarnaum",
        "Irecê", "Ibipeba", "América Dourada", "João Dourado",
        "Canarana", "Ipupiara", "Barro Alto", "Sítio do Quinto",
        "Novo Triunfo", "Heliópolis", "Banzaê", "Fátima",
        "Cícero Dantas", "Ribeira do Pombal", "Nova Soure", "Itapicuru",
        "Acajutiba", "Esplanada", "Cardeal da Silva", "Jandaíra",
        "Conde", "Entre Rios", "Mata de São João", "Camaçari",
        "Lauro de Freitas", "Simões Filho", "Candeias", "São Francisco do Conde",
        "Madre de Deus", "Dias d'Ávila", "Pojuca", "Catu",
        "Alagoinhas", "Araçás", "Terra Nova", "Pedrão",
        "Água Fria", "Olindina", "Inhambupe", "Biritinga",
        "Sátiro Dias", "Aporá", "Acajutiba", "Itanagra",
        "Catu", "Pojuca", "São Sebastião do Passé", "Teodoro Sampaio",
        "Anguera", "Santa Bárbara", "Ichu", "Candeal",
        "Tanquinho", "Coração de Maria", "Antônio Cardoso", "Conceição do Coité",
        "Santo Estêvão", "Rafael Jambeiro", "Ipecaetá", "São Gonçalo dos Campos",
        "São Domingos", "Castro Alves", "Conceição da Feira", "Muritiba",
        "Governador Mangabeira", "Cruz das Almas", "Cachoeira", "Maragogipe",
        "São Félix", "Cabaceiras do Paraguaçu", "Cabaceiras do Paraguaçu", "Saubara",
        "Santo Antônio de Jesus", "Varzedo", "São Miguel das Matas", "Ubaíra",
        "Amargosa", "Elísio Medrado", "Brejões", "Laje",
        "Jiquiriçá", "Santa Inês", "Mutuípe", "Irajuba",
        "Milagres", "Maracás", "Jaguaquara", "Planaltino",
        "Nova Itarana", "Marcionílio Souza", "Manoel Vitorino", "Boa Nova",
        "Dário Meira", "Itagibá", "Ibirataia", "Ubaitaba",
        "Itacaré", "Maraú", "Camamu", "Ituberá",
        "Nilo Peçanha", "Taperoá", "Cairu", "Valença",
        "Nazaré", "Aratuípe", "Jaguaripe", "Vera Cruz",
        "Itaparica", "Salinas da Margarida", "São Francisco do Conde", "Madre de Deus",
        "Simões Filho", "Lauro de Freitas", "Camaçari", "Dias d'Ávila",
    ],
    "Ceará": [
        "Fortaleza", "Caucaia", "Juazeiro do Norte", "Maracanaú",
        "Sobral", "Crato", "Itapipoca", "Maranguape",
        "Iguatu", "Quixadá", "Pacatuba", "Canindé",
        "Crateús", "Aquiraz", "Pacajus", "Russas",
        "Icó", "Tianguá", "Cascavel", "Horizonte",
        "Senador Pompeu", "Quixeramobim", "Aracati", "Guaraciaba do Norte",
        "Camocim", "Acaraú", "Trairi", "Pentecoste",
        "São Gonçalo do Amarante", "Eusébio", "Amontada", "Mombaça",
        "Tauá", "Jaguaribe", "Limoeiro do Norte", "Morada Nova",
        "Barbalha", "Missão Velha", "Brejo Santo", "Jardim",
        "Mauriti", "Barro", "Milagres", "Araripe",
        "Campos Sales", "Potengi", "Santana do Cariri", "Nova Olinda",
        "Farias Brito", "Cariús", "Várzea Alegre", "Cedro",
        "Deputado Irapuan Pinheiro", "Catarina", "Saboeiro", "Solonópole",
        "Itatira", "Paramoti", "Madalena", "Quiterianópolis",
        "Independência", "Arneiroz", "Parambu", "Aiuaba",
        "Tejuçuoca", "Irauçuba", "Uruburetama", "Miraíma",
        "Morrinhos", "Cruz", "Jijoca de Jericoacoara", "Bela Cruz",
        "Marco", "Santana do Acaraú", "Cariré", "Groaíras",
        "Varjota", "Reriutaba", "Hidrolândia", "Ipú",
        "Pires Ferreira", "Ipaporanga", "Cratéus", "Poranga",
        "Ibiapina", "Viçosa do Ceará", "Frecheirinha", "Moraújo",
        "Coreaú", "Meruoca", "Alcântaras", "Senador Sá",
        "Granja", "Chaval", "Barroquinha", "Uruoca",
        "Massapê", "Mucambo", "Forquilha", "Sobral",
        "Santa Quitéria", "Monsenhor Tabosa", "Nova Russas", "Novo Oriente",
        "Tamboril", "Santa Inês", "Boa Viagem", "Banabuiú",
        "Ibicuitinga", "Choró", "Ibaretama", "Potiretama",
        "Alto Santo", "São João do Jaguaribe", "Tabuleiro do Norte", "Jaguaruana",
        "Itaiçaba", "Palhano", "Beberibe", "Fortim",
        "Icapuí", "Aracati", "Jaguaretama", "Jaguaribara",
        "Pereiro", "Ererê", "Iracema", "Potiretama",
        "Quixelô", "Orós", "Ipaumirim", "Lavras da Mangabeira",
        "Umari", "Granjeiro", "Caririaçu", "Juazeiro do Norte",
        "Porteiras", "Abaiara", "Barro", "Penaforte",
        "Jati", "Brejo Santo", "Aurora", "Baixio",
        "Crato", "Aracoiaba", "Ocara", "Redenção",
        "Acarape", "Guaramiranga", "Mulungu", "Baturité",
        "Capistrano", "Itapiúna", "Caridade", "Itatira",
        "General Sampaio", "Umirim", "Apuiarés", "Tururu",
        "Paracuru", "Paraipaba", "Trairí", "Itapajé",
        "Tururu", "São Luís do Curu", "Croatá", "São Benedito",
        "Ubajara", "Carnaubal", "Guaraciaba do Norte", "Ipu",
        "Pindoretama", "Maracanaú", "Maranguape", "Guaiúba",
        "Pacatuba", "Itaitinga", "Chorozinho", "São Gonçalo do Amarante",
        "Caucaia", "Fortaleza", "Maracanaú", "Eusébio",
    ],
    "Distrito Federal": [
        "Brasília", "Ceilândia", "Taguatinga", "Samambaia",
        "Planaltina", "Águas Claras", "Gama", "Guará",
        "Sobradinho", "Recanto das Emas", "Santa Maria", "São Sebastião",
        "Paranoá", "Núcleo Bandeirante", "Candangolândia", "Cruzeiro",
        "Lago Sul", "Lago Norte", "Park Way", "Riacho Fundo",
        "Riacho Fundo II", "Itapoã", "Varjão", "Fercal",
        "Vicente Pires", "Arniqueira", "SCIA/Estrutural", "SIA",
        "Jardim Botânico", "Sobradinho II",

    ],
    "Espírito Santo": [
    "Vitória", "Vila Velha", "Serra", "Cariacica",
    "Linhares", "Cachoeiro de Itapemirim", "Colatina", "Guarapari",
    "São Mateus", "Aracruz", "Viana", "Nova Venécia",
    "Barra de São Francisco", "Marataízes", "Itapemirim", "Piúma",
    "Anchieta", "Iconha", "Rio Novo do Sul", "Alfredo Chaves",
    "Marechal Floriano", "Domingos Martins", "Santa Leopoldina", "Santa Teresa",
    "Fundão", "Ibiraçu", "João Neiva", "Rio Bananal",
    "Sooretama", "Jaguaré", "São Gabriel da Palha", "Vila Valério",
    "água Doce do Norte", "Ecoporanga", "Ponto Belo", "Montanha",
    "Mucurici", "Pinheiros", "Pedro Canário", "Boa Esperança",
    "Conceição da Barra", "São Domingos do Norte", "São Roque do Canaã", "Marilândia",
    "Baixo Guandu", "Aimorés", "Pancas", "Itaguaçu",
    "Itarana", "Afonso Cláudio", "Laranja da Terra", "Irupi",
    "Iúna", "Muniz Freire", "Alegre", "Jerônimo Monteiro",
    "Mimoso do Sul", "Muqui", "Atílio Vivácqua", "Presidente Kennedy",
    "Apiacá", "Bom Jesus do Norte", "Divino de São Lourenço", "Dores do Rio Preto",
    "Guaçuí", "São José do Calçado", "Vargem Alta", "Castelo",
    "Venda Nova do Imigrante", "Conceição do Castelo", "Brejetuba", "Ibitirama",
    "Ibatiba", "São Miguel do Avaí", "Vila Pavão", "Água Doce do Norte",
    "Governador Lindenberg", "Alto Rio Novo", "Mantenópolis", "São Domingos do Norte",
    ],
    "Goiás": [
        "Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde",
        "Luziânia", "Águas Lindas de Goiás", "Valparaíso de Goiás", "Trindade",
        "Formosa", "Novo Gama", "Itumbiara", "Senador Canedo",
        "Catalão", "Jataí", "Planaltina", "Santo Antônio do Descoberto",
        "Goianésia", "Mineiros", "Cristalina", "Caldas Novas",
        "Inhumas", "Morrinhos", "Ceres", "Goianira",
        "Nerópolis", "Hidrolândia", "Bela Vista de Goiás", "Pirenópolis",
        "Cidade Ocidental", "Alexânia", "Jaraguá", "Itaberaí",
        "Iporá", "Quirinópolis", "Porangatu", "Uruaçu",
        "Minaçu", "Niquelândia", "Cocalinho", "São Luís de Montes Belos",
        "Anicuns", "Mozarlândia", "Sanclerlândia", "Britânia",
        "Goiás", "Itapirapuã", "Jussara", "Aruanã",
        "Caiapônia", "Doverlândia", "Palestina de Goiás", "Serranópolis",
        "Chapadão do Céu", "Perolândia", "Portelândia", "Mineiros",
        "Santa Rita do Araguaia", "Aporé", "Itarumã", "Caçu",
        "Gouvelândia", "Lagoa Santa", "Inaciolândia", "Paranaiguara",
        "São Simão", "Cachoeira Alta", "Rio Verde", "Acreúna",
        "Maurilândia", "Turvelândia", "Montividiu", "Santa Helena de Goiás",
        "Castelândia", "Paraúna", "Palmeiras de Goiás", "Cezarina",
        "Edéia", "Indiara", "Itaguari", "Itauçu",
        "Abadia de Goiás", "Aragoiânia", "Guapó", "Varjão",
        "Joviânia", "Mairipotaba", "Cromínia", "Pontalina",
        "Vicentinópolis", "Gouvelândia", "Buriti Alegre", "Água Limpa",
        "Ipameri", "Orizona", "Vianópolis", "Pires do Rio",
        "Santa Cruz de Goiás", "Urutaí", "Leopoldo de Bulhões", "Gameleira de Goiás",
        "Silvânia", "Brasília de Minas", "Anápolis", "Damolândia",
        "Petrolina de Goiás", "Nova Veneza", "Ouro Verde de Goiás", "Terezópolis de Goiás",
        "Bonfinópolis", "Brazabrantes", "Cachoeira de Goiás", "Córrego do Ouro",
        "Fazenda Nova", "Mossâmedes", "Sanclerlândia", "São João da Paraúna",
        "Aurilândia", "Americano do Brasil", "Israelândia", "Ivolândia",
        "Jesúpolis", "Heitoraí", "Itaberaí", "Uruana",
        "Rialma", "Rianápolis", "Carmo do Rio Verde", "Ipiranga de Goiás",
        "Santa Isabel", "Guarinos", "Hidrolina", "São Luís do Norte",
        "Barro Alto", "Goianésia", "Vila Propício", "Mimoso de Goiás",
        "Planaltina", "Água Fria de Goiás", "Cabeceiras", "Buritis",
        "Vila Boa", "Simolândia", "Alvorada do Norte", "Mambaí",
        "Posse", "Sítio d'Abadia", "Iaciara", "Flores de Goiás",
        "Damianópolis", "Guarani de Goiás", "São Domingos", "Divinópolis de Goiás",
        "Campos Belos", "Monte Alegre de Goiás", "Cavalcante", "Colinas do Sul",
        "Alto Paraíso de Goiás", "Teresina de Goiás", "Nova Roma", "São João d'Aliança",
        "Formosa", "Planaltina", "Padre Bernardo", "Cocalzinho de Goiás",
        "Corumbá de Goiás", "Abadiânia", "Gameleira de Goiás", "Silvânia",
        "Palmelo", "Santa Cruz de Goiás", "Professor Jamil", "Gouvelândia",
        "Caldazinha", "Senador Canedo", "Aparecida de Goiânia", "Goiânia",
    ],
    "Maranhão": [
        "São Luís", "Imperatriz", "São José de Ribamar", "Timon",
        "Caxias", "Codó", "Paço do Lumiar", "Açailândia",
        "Bacabal", "Balsas", "Santa Inês", "Pinheiro",
        "Chapadinha", "Itapecuru Mirim", "Santa Luzia", "Barra do Corda",
        "Coroatá", "Viana", "Pedreiras", "Grajaú",
        "Presidente Dutra", "Zé Doca", "Colinas", "Carolina",
        "Porto Franco", "Estreito", "Pindaré-Mirim", "Alto Alegre do Pindaré",
        "Buriticupu", "Açailândia", "Amarante do Maranhão", "Sítio Novo",
        "Lago da Pedra", "Lago dos Rodrigues", "Lago do Junco", "Pedreiras",
        "Capinzal do Norte", "Bernardo do Mearim", "São Raimundo do Doca Bezerra", "Esperantinópolis",
        "Igarapé Grande", "São Mateus do Maranhão", "São Luís Gonzaga do Maranhão", "Lima Campos",
        "Trizidela do Vale", "Altamira do Maranhão", "São Roberto", "Olho d'Água das Cunhãs",
        "Pio XII", "Lago Verde", "São João do Soter", "São Benedito do Rio Preto",
        "Codó", "Timbiras", "Coroatá", "Aldeias Altas",
        "Peritoró", "Duque Bacelar", "Parnarama", "Matões",
        "Gonçalves Dias", "Governador Archer", "Governador Eugênio Barros", "Presidente Vargas",
        "São Raimundo das Mangabeiras", "Fortuna", "Colinas", "Mirador",
        "Fernando Falcão", "Sucupira do Riachão", "Loreto", "São João dos Patos",
        "Barão de Grajaú", "Passagem Franca", "Sambaíba", "Tasso Fragoso",
        "Riachão", "Carolina", "Estreito", "Imperatriz",
        "João Lisboa", "Montes Altos", "Sítio Novo", "Lajeado Novo",
        "Amarante do Maranhão", "Campestre do Maranhão", "Senador La Rocque", "Porto Franco",
        "Governador Edison Lobão", "Davinópolis", "Açailândia", "Cidelândia",
        "Vila Nova dos Martírios", "São Pedro da Água Branca", "Buritirana", "Angico",
        "Itinga do Maranhão", "Amarante do Maranhão", "Bom Jesus das Selvas", "Arame",
        "Sítio Novo", "Buriticupu", "Bom Jardim", "Santa Luzia do Paruá",
        "Maranhãozinho", "Zé Doca", "Pindaré-Mirim", "Monção",
        "Pinheiro", "Olinda Nova do Maranhão", "São João Batista", "Palmeirândia",
        "Peri Mirim", "Alcântara", "São Luís", "Paço do Lumiar",
        "São José de Ribamar", "Raposa", "Icatu", "Bacabeira",
        "Rosário", "Axixá", "Morros", "Humberto de Campos",
        "Primeira Cruz", "Urbano Santos", "Chapadinha", "Brejo",
        "Anapurus", "Mata Roma", "São Bernardo", "Belágua",
        "Magalhães de Almeida", "Santa Quitéria do Maranhão", "Mirinzal", "Cururupu",
        "Serrano do Maranhão", "Bequimão", "Apicum-Açu", "Guimarães",
        "Cedral", "Cajapió", "Anajatuba", "Vitória do Mearim",
        "Arari", "São Bento", "Penalva", "Viana",
        "Matinha", "Tufilândia", "Pedro do Rosário", "Bacuri",
        "Caxias", "Aldeias Altas", "São João do Sóter", "Timon",
        "Água Doce do Maranhão", "Buriti", "Tutóia", "Araioses",
        "Paulino Neves", "Barreirinhas", "Santo Amaro do Maranhão", "Humberto de Campos",
        "Central do Maranhão", "São José de Ribamar", "Paço do Lumiar", "São Luís",
    ],
    "Mato Grosso": [
        "Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop",
        "Tangará da Serra", "Cáceres", "Sorriso", "Lucas do Rio Verde",
        "Primavera do Leste", "Barra do Garças", "Alta Floresta", "Pontes e Lacerda",
        "Nova Mutum", "Campo Verde", "Juara", "Guarantã do Norte",
        "Colíder", "Peixoto de Azevedo", "Matupá", "Terra Nova do Norte",
        "Novo Mundo", "Carlinda", "Nova Canaã do Norte", "Itaúba",
        "Nova Santa Helena", "Marcelândia", "Juruena", "Apiacás",
        "Nova Bandeirante", "Paranaíta", "Alta Floresta", "Colíder",
        "Nortelândia", "Nova Maringá", "Tapurah", "Santa Rita do Trivelato",
        "Sorriso", "Lucas do Rio Verde", "Nova Ubiratã", "Ipiranga do Norte",
        "Itiquira", "Pedra Preta", "São Pedro da Cipa", "Jaciara",
        "Juscimeira", "São José do Povo", "Guiratinga", "Tesouro",
        "Torixoréu", "General Carneiro", "Ribeirãozinho", "Araguainha",
        "Ponte Branca", "Alto Araguaia", "Alto Garças", "Alto Taquari",
        "Rondonópolis", "Poxoréu", "Dom Aquino", "Barão de Melgaço",
        "Santo Antônio do Leverger", "Várzea Grande", "Cuiabá", "Chapada dos Guimarães",
        "Nova Brasilândia", "Planalto da Serra", "Paranatinga", "Água Boa",
        "Nova Xavantina", "Canarana", "Querência", "São Félix do Araguaia",
        "Porto Alegre do Norte", "Vila Rica", "Confresa", "Santa Cruz do Xingu",
        "São José do Xingu", "Canabrava do Norte", "Ribeirão Cascalheira", "Novo São Joaquim",
        "Campinápolis", "Santo Antônio do Leste", "Nova Nazaré", "Cocalinho",
        "Barra do Garças", "Pontal do Araguaia", "Araguaiana", "Araputanga",
        "Mirassol d'Oeste", "Indiavaí", "Reserva do Cabaçal", "Salto do Céu",
        "Figueirópolis d'Oeste", "Lambari d'Oeste", "Glória d'Oeste", "Porto Estrela",
        "Barra do Bugres", "Tangará da Serra", "Nova Olímpia", "Denise",
        "Campo Novo do Parecis", "Diamantino", "Nobres", "Rosário Oeste",
        "Acorizal", "Jangada", "Côco", "Poconé",
        "Cáceres", "Curvelândia", "Rio Branco", "Jauru",
        "Conquista d'Oeste", "Vila Bela da Santíssima Trindade", "Pontes e Lacerda", "Comodoro",
        "Sapezal", "Campo Novo do Parecis", "Brasnorte", "Juara",
        "Aripuanã", "Rondolândia", "Cotriguaçu", "Colniza",
        "Castanheira", "Rondolândia", "Aripuanã", "Nova Monte Verde",
    ],
    "Mato Grosso do Sul": [
        "Campo Grande", "Dourados", "Três Lagoas", "Corumbá",
        "Ponta Porã", "Naviraí", "Nova Andradina", "Aquidauana",
        "Sidrolândia", "Paranaíba", "Maracaju", "Coxim",
        "São Gabriel do Oeste", "Chapadão do Sul", "Cassilândia", "Costa Rica",
        "Sonora", "Pedro Gomes", "Camapuã", "Rio Verde de Mato Grosso",
        "Jaraguari", "Rochedo", "Bandeirantes", "Ribas do Rio Pardo",
        "Água Clara", "Brasilândia", "Selvíria", "Aparecida do Taboado",
        "Inocência", "Paraíso das Águas", "Alcinópolis", "Figueirão",
        "Terenos", "Campo Grande", "Dois Irmãos do Buriti", "Anastácio",
        "Aquidauana", "Miranda", "Bodoquena", "Bonito",
        "Jardim", "Bela Vista", "Antônio João", "Ponta Porã",
        "Aral Moreira", "Coronel Sapucaia", "Paranhos", "Sete Quedas",
        "Japorã", "Mundo Novo", "Eldorado", "Iguatemi",
        "Itaquiraí", "Naviraí", "Juti", "Caarapó",
        "Laguna Carapã", "Douradina", "Dourados", "Fátima do Sul",
        "Glória de Dourados", "Deodápolis", "Jateí", "Vicentina",
        "Angélica", "Nova Alvorada do Sul", "Bataguassu", "Anaurilândia",
        "Nova Andradina", "Taquarussu", "Três Lagoas", "Aparecida do Taboado",
        "Paranaíba", "Inocência", "Água Clara", "Ribas do Rio Pardo",
        "Porto Murtinho", "Caracol", "Bela Vista", "Guia Lopes da Laguna",
        "Nioaque", "Rio Negro", "Corguinho", "São Gabriel do Oeste",
    ],
    "Minas Gerais": [
        "Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora",
        "Betim", "Montes Claros", "Ribeirão das Neves", "Uberaba",
        "Governador Valadares", "Ipatinga", "Sete Lagoas", "Divinópolis",
        "Santa Luzia", "Ibirité", "Poços de Caldas", "Patos de Minas",
        "Pouso Alegre", "Teófilo Otoni", "Barbacena", "Sabará",
        "Varginha", "Conselheiro Lafaiete", "Vespasiano", "Itabira",
        "Coronel Fabriciano", "Cataguases", "Lavras", "Passos",
        "Muriaé", "Araguari", "Ubá", "Nova Lima",
        "Ituiutaba", "Formiga", "Ouro Preto", "Caratinga",
        "Diamantina", "Alfenas", "Itaúna", "João Monlevade",
        "Patrocínio", "Paracatu", "Unaí", "Pirapora",
        "Três Corações", "São João del-Rei", "Araxá", "Frutal",
        "Curvelo", "Timóteo", "Manhuaçu", "Viçosa",
        "Itajubá", "Ponte Nova", "Congonhas", "Mariana",
        "Três Pontas", "Leopoldina", "Oliveira", "Lagoa Santa",
        "Pedro Leopoldo", "Esmeraldas", "Brumadinho", "Nova Serrana",
        "Bom Despacho", "Campos Gerais", "Guaxupé", "São Sebastião do Paraíso",
        "Monte Carmelo", "Iturama", "Capinópolis", "Tupaciguara",
        "Centralina", "Abadia dos Dourados", "Coromandel", "Vazante",
        "João Pinheiro", "Brasilândia de Minas", "Lagamar", "Presidente Olegário",
        "Guarda-Mor", "Lagoa Grande", "Natalândia", "Bonfinópolis de Minas",
        "Uruana de Minas", "Dom Bosco", "Arinos", "Buritis",
        "Cabeceira Grande", "Formoso", "Riachinho", "São Romão",
        "Januária", "Itacarambi", "Manga", "Matias Cardoso",
        "Cônego Marinho", "Lontra", "Mirabela", "Francisco Sá",
        "Bocaiúva", "Joaquim Felício", "Augusto de Lima", "Buenópolis",
        "Corinto", "Morro da Garça", "Inimutaba", "Presidente Juscelino",
        "Santo Hipólito", "Paraopeba", "Caetanópolis", "Jequitibá",
        "Pompéu", "Abaeté", "Morada Nova de Minas", "São Gotardo",
        "Tiros", "Matutina", "Quartel Geral", "Martinho Campos",
        "Paineiras", "Cedro do Abaeté", "Estrela do Indaiá", "Bambuí",
        "Medeiros", "Tapiraí", "Piumhi", "Pains",
        "Córrego Fundo", "Itapecerica", "Carmo do Cajuru", "São Gonçalo do Pará",
        "Conceição do Pará", "Igaratinga", "Leandro Ferreira", "Maravilhas",
        "Pequi", "Florestal", "Paraíso", "Onça de Pitangui",
        "Pitangui", "Bonfim", "Fortuna de Minas", "Prudente de Morais",
        "Funilândia", "Baldim", "Jaboticatubas", "Capim Branco",
        "Confins", "Matozinhos", "São José da Lapa", "Igarapé",
        "Mário Campos", "São Joaquim de Bicas", "Mateus Leme", "Juatuba",
        "Itatiaiuçu", "Crucilândia", "Itaguara", "Belo Vale",
        "Jeceaba", "Entre Rios de Minas", "São Brás do Suaçuí", "Itaverava",
        "Catas Altas", "Santa Bárbara", "Barão de Cocais", "São Gonçalo do Rio Abaixo",
        "Nova Era", "Antônio Dias", "Belo Oriente", "Mesquita",
        "Naque", "Açucena", "Fernandes Tourinho", "São João Evangelista",
        "Guanhães", "Sabinópolis", "Coluna", "Virgem da Lapa",
        "Araçuaí", "Itinga", "Coronel Murta", "Rubelita",
        "Pedra Azul", "Jacinto", "Salto da Divisa", "Almenara",
        "Rio do Prado", "Palmópolis", "Felisburgo", "Bandeira",
        "Santa Maria do Salto", "Jordânia", "Santo Antônio do Jacinto", "Medina",
        "Jequitinhonha", "Joaíma", "Ponto dos Volantes", "Cachoeira de Pajeú",
        "Mata Verde", "Curral de Dentro", "Águas Vermelhas", "Fruta de Leite",
        "Novorizonte", "Grão Mogol", "Cristália", "Botumirim",
        "Itacambira", "Olhos-d'Água", "Monjolos", "Lassance",
        "Várzea da Palma", "Ibiaí", "Buritizeiro", "Varzelândia",
        "Coração de Jesus", "São João da Lagoa", "Claro dos Poções", "Capitão Enéas",
        "Glaucilândia", "Juramento", "Riacho dos Machados", "Pai Pedro",
        "Serranópolis de Minas", "Catuti", "Espinosa", "Mamonas",
        "Montezuma", "Indaiabira", "Santo Antônio do Retiro", "Ninheira",
        "São João do Paraíso", "Taiobeiras", "Rio Pardo de Minas", "Divisa Alegre",
        "Santa Cruz de Salinas", "Salinas", "Berizal", "Vargem Grande do Rio Pardo",
        "Aimorés", "Itueta", "Resplendor", "Galiléia",
        "Conselheiro Pena", "Periquito", "Matipó", "São Domingos do Prata",
        "Rio Casca", "Abre Campo", "Reduto", "Manhumirim",
        "Simonésia", "Alto Jequitibá", "Carangola", "Tombos",
        "Divino", "Espera Feliz", "Fervedouro", "Pedra Bonita",
        "Alto Caparaó", "Caparaó", "São José do Mantimento", "Lajinha",
        "Mutum", "Conceição de Ipanema", "Ipanema", "Pocrane",
        "Tarumirim", "Sobrália", "Engenheiro Caldas", "São João do Oriente",
        "Alvarenga", "Campanário", "Itanhomi", "Coroaci",
        "Virginópolis", "Divinolândia de Minas", "Paulistas", "Peçanha",
        "Sardoá", "Materlândia", "Dores de Guanhães", "Santa Maria do Suaçuí",
        "Frei Inocêncio", "Jampruca", "São Geraldo da Piedade", "São Pedro do Suaçuí",
        "Água Boa", "Berilo", "Capelinha", "Minas Novas",
        "Turmalina", "Veredinha", "Chapada do Norte", "Setubinha",
        "Novo Cruzeiro", "Padre Paraíso", "Caraí", "Pescador",
        "Malacacheta", "Itaipé", "Ladainha", "Crisólita",
        "Ouro Verde de Minas", "São João do Manteninha", "Ataléia", "Franciscópolis",
        "Frei Gaspar", "Santa Helena de Minas", "Nanuque", "Machacalis",
        "Serra dos Aimorés", "Bertópolis", "São José do Divino", "Umburatiba",
        "Fronteira dos Vales", "Jequitinhonha", "Joaíma", "Almenara",
        "Jordânia", "Santo Antônio do Jacinto", "Jacinto", "Salto da Divisa",
        "Palmópolis", "Felisburgo", "Rio do Prado", "Bandeira",
        "Pedra Azul", "Coronel Murta", "Virgem da Lapa", "Araçuaí",
        "Itaobim", "Itinga", "Ponto dos Volantes", "Cachoeira de Pajeú",
        "Rubelita", "Taiobeiras", "Novorizonte", "Fruta de Leite",
        "Curral de Dentro", "Montezuma", "Ninheira", "Indaiabira",
        "Santo Antônio do Retiro", "Mamonas", "Catuti", "Espinosa",
        "Pai Pedro", "Serranópolis de Minas", "Riacho dos Machados", "Juramento",
        "Glaucilândia", "Capitão Enéas", "Claro dos Poções", "São João da Lagoa",
        "Coração de Jesus", "Varzelândia", "Lontra", "Mirabela",
        "Cônego Marinho", "Matias Cardoso", "Manga", "Itacarambi",
        "Januária", "São Romão", "Riachinho", "Formoso",
        "Dom Bosco", "Uruana de Minas", "Bonfinópolis de Minas", "Cabeceira Grande",
        "Buritis", "Arinos", "Unaí", "Paracatu",
        "Lagoa Grande", "Guarda-Mor", "Presidente Olegário", "Lagamar",
        "Brasilândia de Minas", "João Pinheiro", "Vazante", "Coromandel",
        "Abadia dos Dourados", "Monte Carmelo", "Patrocínio", "Patos de Minas",
        "São Gonçalo do Abaeté", "Varjão de Minas", "Tiros", "São Gotardo",
        "Carmo do Paranaíba", "Arapuá", "Rio Paranaíba", "Santa Rosa da Serra",
        "Matutina", "Quartel Geral", "Lagoa Formosa", "Campos Altos",
        "Ibiá", "Pratinha", "Perdizes", "Sacramento",
        "Conquista", "Planura", "Fronteira", "Comendador Gomes",
        "Itapagipe", "Pirajuba", "Canápolis", "Capinópolis",
        "Tupaciguara", "Centralina", "Araporã", "Ituiutaba",
        "Gurinhatã", "Ipiaçu", "Santa Vitória", "Iturama",
        "Limeira do Oeste", "União de Minas", "Carneirinho", "Campina Verde",
        "Frutal", "Água Comprida", "Conceição das Alagoas", "Uberaba",
        "Veríssimo", "Mourão", "Pedrinópolis", "Pirajuba",
        "Delta", "Conceição das Alagoas", "Planura", "Fronteira",
        "Itapagipe", "Comendador Gomes", "Canápolis", "Ituiutaba",
        "Prata", "Monte Alegre de Minas", "Uberlândia", "Araguari",
        "Indianópolis", "Romaria", "Abadia dos Dourados", "Cascalho Rico",
        "Douradoquara", "Grupiara", "Coromandel", "Estrela do Sul",
        "Iraí de Minas", "Cruzeiro da Fortaleza", "Guimarânia", "Patrocínio",
        "Serra do Salitre", "Presidente Olegário", "Varjão de Minas", "Lagoa Formosa",
        "Arapuá", "Rio Paranaíba", "Carmo do Paranaíba", "São Gotardo",
        "Matutina", "Quartel Geral", "Paineiras", "Cedro do Abaeté",
        "Morada Nova de Minas", "Pompéu", "Jequitibá", "Caetanópolis",
        "Paraopeba", "Santo Hipólito", "Presidente Juscelino", "Inimutaba",
        "Morro da Garça", "Corinto", "Buenópolis", "Augusto de Lima",
        "Joaquim Felício", "Bocaiúva", "Francisco Sá", "Mirabela",
        "Lontra", "Grão Mogol", "Cristália", "Botumirim",
        "Itacambira", "Olhos-d'Água", "Monjolos", "Lassance",
    ],
    "Pará": [
        "Belém", "Ananindeua", "Santarém", "Marabá",
        "Castanhal", "Parauapebas", "Altamira", "Abaetetuba",
        "Cametá", "Marituba", "Tucuruí", "Barcarena",
        "Breves", "Itaituba", "Bragança", "Paragominas",
        "Redenção", "Tailândia", "Benevides", "Tomé-Açu",
        "Dom Eliseu", "Rondon do Pará", "Capanema", "Vigia",
        "São Miguel do Guamá", "Viseu", "Salinópolis", "Moju",
        "Novo Progresso", "São Félix do Xingu", "Ourilândia do Norte", "Bannach",
        "Cumaru do Norte", "Tucumã", "Xinguara", "Rio Maria",
        "Conceição do Araguaia", "Redenção", "Floresta do Araguaia", "Pau d'Arco",
        "São Domingos do Araguaia", "Abel Figueiredo", "Bom Jesus do Tocantins", "Marabá",
        "Curionópolis", "Eldorado dos Carajás", "São Geraldo do Araguaia", "Sapucaia",
        "Piçarra", "Água Azul do Norte", "Canaã dos Carajás", "Parauapebas",
        "Palestina do Pará", "São João do Araguaia", "São Domingos do Capim", "Irituia",
        "Mãe do Rio", "Aurora do Pará", "Ipixuna do Pará", "Paragominas",
        "Ulianópolis", "Dom Eliseu", "Rondon do Pará", "Goianésia do Pará",
        "Novo Repartimento", "Tucuruí", "Jacundá", "Nova Ipixuna",
        "Itupiranga", "Baião", "Mocajuba", "Limoeiro do Ajuru",
        "Cametá", "Oeiras do Pará", "Portel", "Bagre",
        "Gurupá", "Melgaço", "Breves", "Curralinho",
        "São Sebastião da Boa Vista", "Afuá", "Chaves", "Soure",
        "Salvaterra", "Cachoeira do Arari", "Santa Cruz do Arari", "Muaná",
        "Ponta de Pedras", "Anajás", "São João de Pirabas", "Primavera",
        "Santana do Araguaia", "Serra dos Carajás", "Oriximiná", "Óbidos",
        "Alenquer", "Monte Alegre", "Prainha", "Porto de Moz",
        "Almeirim", "Vitória do Xingu", "Brasil Novo", "Medicilândia",
        "Uruará", "Placas", "Rurópolis", "Trairão",
        "Santarém", "Belterra", "Mojuí dos Campos", "Aveiro",
        "Itaituba", "Jacareacanga", "Novo Progresso", "Castelo de Sonhos",
        "Terra Santa", "Faro", "Juruti", "Parintins",
        "Marapanim", "São Caetano de Odivelas", "Curuçá", "Terra Alta",
        "Colares", "São João da Ponta", "Bujaru", "Concórdia do Pará",
        "Acará", "Tomé-Açu", "Tailândia", "Moju",
        "Igarapé-Miri", "Limoeiro do Ajuru", "Mocajuba", "Baião",
    ],
    "Paraíba": [
        "João Pessoa", "Campina Grande", "Santa Rita", "Patos",
        "Bayeux", "Sousa", "Cajazeiras", "Cabedelo",
        "Guarabira", "Sapé", "Mamanguape", "Rio Tinto",
        "Esperança", "Queimadas", "Lagoa Seca", "Alagoa Grande",
        "Itabaiana", "Picuí", "Cuité", "Nova Floresta",
        "Pedras de Fogo", "Cruz do Espírito Santo", "Conde", "Alhandra",
        "Caaporã", "Pitimbu", "Mataraca", "Jacaraú",
        "Lucena", "Marcação", "Baía da Traição", "Rio Tinto",
        "Capim", "Lagoa de Dentro", "Mulungu", "Borborema",
        "Areia", "Bananeiras", "Solânea", "Remígio",
        "Montadas", "Massaranduba", "Pirpirituba", "Pilões",
        "Belém", "Serra da Raiz", "Logradouro", "Cuitegi",
        "Duas Estradas", "Dona Inês", "Casserengue", "Araruna",
        "Cacimba de Dentro", "Damião", "Barra de Santa Rosa", "Cubati",
        "Pedra Lavrada", "Frei Martinho", "Sossego", "Nova Palmeira",
        "Seridó", "Juazeirinho", "Estrada", "Tenório",
        "São João do Cariri", "Cabaceiras", "Boqueirão", "Caraúbas",
        "Alcantil", "Caturité", "Aroeiras", "Natuba",
        "Umbuzeiro", "Gado Bravo", "São Domingos do Cariri", "Camalaú",
        "Congo", "Serra Branca", "Sumé", "Prata",
        "Amparo", "São José dos Cordeiros", "Livramento", "Monteiro",
        "Ouro Velho", "Zabelê", "Correntes", "Gurjão",
        "Junco do Seridó", "Santa Luzia", "São Mamede", "Várzea",
        "Passagem", "Lagoa", "Mãe d'Água", "Água Branca",
        "Cacimbas", "Desterro", "Salgadinho", "Imaculada",
        "Juru", "Tavares", "Santana de Mangueira", "Serra Grande",
        "Boa Ventura", "Ibiara", "Diamante", "Conceição",
        "Santana dos Garrotes", "Patos", "Quixaba", "São Bentinho",
        "Paulista", "Pombal", "Aparecida", "Lagoa do Ouro",
        "São Domingos", "Vista Serrana", "Riacho dos Cavalos", "Brejo dos Santos",
        "Catolé do Rocha", "Bom Sucesso", "Jericó", "São Bento",
        "Brejo do Cruz", "Mato Grosso", "Paulista", "São José do Bonfim",
        "Cacimba de Areia", "Belém do Brejo do Cruz", "Caiçara", "Três Rios",
        "Triunfo", "Soledade", "Teixeira", "Manaíra",
        "Princesa Isabel", "Piancó", "Emas", "Coremas",
        "Catingueira", "São José de Espinharas", "Patos", "Malta",
        "Paulista", "São José do Bonfim", "Cacimba de Areia", "Santa Inês",
        "Itaporanga", "Serra do Teixeira", "Aguiar", "São José de Caiana",
        "Igaracy", "Boa Vista", "Cajazeirinhas", "Santa Cruz",
        "Sousa", "Vieirópolis", "Uiraúna", "Bernardino Batista",
        "Cajazeiras", "Poço de José de Moura", "São José de Piranhas", "Triunfo",
        "Bonito de Santa Fé", "Cachoeira dos Índios", "Monte Horebe", "Bom Jesus",
        "São Francisco", "Zabelê", "Nazarezinho", "Santa Helena",
    ],
    "Paraná": [
        "Curitiba", "Londrina", "Maringá", "Ponta Grossa",
        "Cascavel", "São José dos Pinhais", "Foz do Iguaçu", "Colombo",
        "Guarapuava", "Paranaguá", "Araucária", "Toledo",
        "Apucarana", "Pinhais", "Campo Largo", "Almirante Tamandaré",
        "Umuarama", "Piraquara", "Cambé", "Fazenda Rio Grande",
        "Sarandi", "Paranavaí", "Francisco Beltrão", "Pato Branco",
        "Rolândia", "Cianorte", "Arapongas", "Telêmaco Borba",
        "Campo Mourão", "Irati", "Cornélio Procópio", "Bandeirantes",
        "Ibiporã", "Marialva", "Mandaguaçu", "Astorga",
        "Jandaia do Sul", "Mandaguari", "Ivaiporã", "Cândido de Abreu",
        "Faxinal", "Reserva", "Ortigueira", "Tibagi",
        "Castro", "Piraí do Sul", "Jaguariaíva", "Sengés",
        "Tomazina", "Wenceslau Braz", "Ibaiti", "Quatiguá",
        "Japira", "Jaboti", "Conselheiro Mairinck", "Abatiá",
        "Ribeirão do Pinhal", "Cambará", "Jacarezinho", "Santo Antônio da Platina",
        "Carlópolis", "Joaquim Távora", "Guapirama", "Pinhalão",
        "Andirá", "Barra do Jacaré", "Leópolis", "Assaí",
        "Uraí", "Nova América da Colina", "São Jerônimo da Serra", "Tamarana",
        "Londrina", "Sertanópolis", "Rancho Alegre", "Santa Cecília do Pavão",
        "São Sebastião da Amoreira", "Nova Santa Bárbara", "Primeiro de Maio", "Alvorada do Sul",
        "Florestópolis", "Porecatu", "Centenário do Sul", "Prado Ferreira",
        "Miraselva", "Lupionópolis", "Astorga", "Atalaia",
        "Munhoz de Mello", "Alto Paraná", "Colorado", "Lobato",
        "Jaguapitã", "Guaraci", "Santa Inês", "Flórida",
        "Itaguajé", "Uniflor", "Maringá", "Paiçandu",
        "Ourizona", "Presidente Castelo Branco", "Ângulo", "Iguaraçu",
        "Doutor Camargo", "Nossa Senhora das Graças", "Ivatuba", "Floresta",
        "Rancho Alegre d'Oeste", "Campina da Lagoa", "Ubiratã", "Altamira do Paraná",
        "Formosa do Oeste", "Juranda", "Mamborê", "Barbosa Ferraz",
        "Boa Esperança", "Roncador", "Luiziana", "Laranjal",
        "Palmital", "Mato Rico", "Pitanga", "Santa Maria do Oeste",
        "Turvo", "Guarapuava", "Pinhão", "Reserva do Iguaçu",
        "Palmas", "Clevelândia", "Coronel Vivida", "Chopinzinho",
        "São João", "Sulina", "Flor da Serra do Sul", "Marmeleiro",
        "Renascença", "Salto do Lontra", "Nova Prata do Iguaçu", "Cruzeiro do Iguaçu",
        "Dois Vizinhos", "Verê", "São Jorge d'Oeste", "Mangueirinha",
        "Honório Serpa", "Coronel Domingos Soares", "Palmas", "General Carneiro",
        "Bituruna", "Cruz Machado", "Paula Freitas", "Paulo Frontin",
        "São Mateus do Sul", "Antônio Olinto", "São João do Triunfo", "Rebouças",
        "Imbituva", "Ipiranga", "Ivaí", "Guamiranga",
        "Fernandes Pinheiro", "Teixeira Soares", "Ponta Grossa", "Palmeira",
        "Lapa", "Contenda", "Balsa Nova", "Campo Largo",
        "Araucária", "Fazenda Rio Grande", "Mandirituba", "Quitandinha",
        "Agudos do Sul", "Tijucas do Sul", "São José dos Pinhais", "Curitiba",
        "Piraquara", "Pinhais", "Colombo", "Almirante Tamandaré",
        "Campo Magro", "Itaperuçu", "Rio Branco do Sul", "Bocaiúva do Sul",
        "Tunas do Paraná", "Cerro Azul", "Doutor Ulysses", "Adrianópolis",
        "Guaraqueçaba", "Antonina", "Morretes", "Paranaguá",
        "Pontal do Paraná", "Matinhos", "Guaratuba", "São José dos Pinhais",
        "Foz do Iguaçu", "Medianeira", "Matelândia", "Céu Azul",
        "Cascavel", "Santa Tereza do Oeste", "Corbélia", "Cafelândia",
        "Quedas do Iguaçu", "Laranjeiras do Sul", "Rio Bonito do Iguaçu", "Cantagalo",
        "Virmond", "Catanduvas", "Ibema", "Guaraniaçu",
        "Diamante do Sul", "Nova Aurora", "Jesuítas", "Assis Chateaubriand",
        "Maripá", "Palotina", "São José das Palmeiras", "Mercedes",
        "Quatro Pontes", "Pato Bragado", "Guaíra", "Terra Roxa",
        "Altônia", "São Jorge do Patrocínio", "Esperança Nova", "Icaraíma",
        "Xambrê", "Tapira", "Cidade Gaúcha", "Cruzeiro do Oeste",
        "Rondon", "Goioerê", "Moreira Sales", "Janiópolis",
        "Mariluz", "Cafezal do Sul", "Douradina", "Umuarama",
    ],
    "Pernambuco": [
        "Recife", "Caruaru", "Olinda", "Petrolina",
        "Paulista", "Jaboatão dos Guararapes", "Camaçari", "Camaragibe",
        "Garanhuns", "Vitória de Santo Antão", "Igarassu", "São Lourenço da Mata",
        "Santa Cruz do Capibaribe", "Abreu e Lima", "Cabo de Santo Agostinho", "Ipojuca",
        "Serra Talhada", "Araripina", "Ouricuri", "Salgueiro",
        "Arcoverde", "Bezerros", "Gravatá", "Caruaru",
        "Belo Jardim", "Pesqueira", "Bonito", "Brejo da Madre de Deus",
        "São Bento do Una", "Sanharó", "Tacaimbó", "Poção",
        "Alagoinha", "Venturosa", "Pedra", "Buíque",
        "Tupanatinga", "Ibimirim", "Inajá", "Tacaratu",
        "Jatobá", "Itacuruba", "Carnaubeira da Penha", "Floresta",
        "Belém de São Francisco", "Cabrobó", "Orocó", "Petrolândia",
        "Santa Maria da Boa Vista", "Lagoa Grande", "Dormentes", "Petrolina",
        "Afrânio", "Bodocó", "Exu", "Moreilândia",
        "Ipubi", "Trindade", "Araripina", "Granito",
        "Santa Cruz", "Cedro", "Verdejante", "Serrita",
        "Mirandiba", "Salgueiro", "São José do Belmonte", "Terra Nova",
        "Calumbi", "Flores", "Iguaraci", "Afogados da Ingazeira",
        "Tuparetama", "Carnaíba", "Santa Cruz da Baixa Verde", "Serra Talhada",
        "Betânia", "Custódia", "Sertânia", "Sumé",
        "Brejinho", "Solidão", "Tabira", "Itapetim",
        "Manaíra", "Santa Terezinha", "Quixaba", "São José do Egito",
        "Monteiro", "Imaculada", "Água Branca", "Brejão",
        "Paranatama", "Capoeiras", "Lajedo", "Palmeirina",
        "São João", "Correntes", "Jucati", "Jupi",
        "Lagoa do Ouro", "Palmerina", "Itaíba", "Águas Belas",
        "Saloá", "Brejão", "Canhotinho", "Garanhuns",
        "Angelim", "São Pedro do Caçador", "Calcado", "Quipapá",
        "Catende", "Ribeirão", "Palmares", "Barreiros",
        "São Benedito do Sul", "Amaraji", "Escada", "Ipiaú",
        "Primavera", "Água Preta", "Joaquim Nabuco", "Lagoa dos Gatos",
        "Maraial", "Xexéu", "Bom Conselho", "Terezinha",
        "Iati", "Itapetim", "São Caitano", "Agrestina",
        "Cachoeirinha", "Riacho das Almas", "Taquaritinga do Norte", "Vertente do Lério",
        "Vertentes", "Frei Miguelinho", "Santa Cruz do Capibaribe", "Toritama",
        "Casinhas", "Surubim", "Limoeiro", "Bom Jardim",
        "Orobó", "Machados", "Nazaré da Mata", "Tracunhaém",
        "Carpina", "Lagoa do Carro", "Paudalho", "Buenos Aires",
        "Aliança", "Itaquitinga", "Condado", "Ferreiros",
        "Timbaúba", "Camutanga", "Vicência", "Macaparana",
        "São Vicente Ferrer", "Feira Nova", "Passira", "Salgadinho",
        "Cumaru", "Pesqueira", "Poção", "Alagoinha",
        "Olinda", "Recife", "Paulista", "Abreu e Lima",
        "Igarassu", "Itamaracá", "Itapissuma", "Araçoiaba",
    ],
    "Piauí": [
        "Teresina", "Parnaíba", "Picos", "Piripiri",
        "Floriano", "Campo Maior", "Barras", "Esperantina",
        "José de Freitas", "Oeiras", "São Raimundo Nonato", "Corrente",
        "Bom Jesus", "Uruçuí", "Altos", "Demerval Lobão",
        "União", "Miguel Alves", "Porto", "Batalha",
        "Água Branca", "Valença do Piauí", "Picos", "Pio IX",
        "Simões", "Paulistana", "Fronteiras", "Caldeirão Grande do Piauí",
        "Acauã", "Betânia do Piauí", "São Julião", "Ipubi",
        "Jacobina do Piauí", "Queimada Nova", "São Lourenço do Piauí", "Colônia do Piauí",
        "Aroazes", "Monsenhor Hipólito", "Itainópolis", "Alagoinha do Piauí",
        "Alegrete do Piauí", "Belém do Piauí", "Santana do Piauí", "Wall Ferraz",
        "Francisco Macedo", "Vera Mendes", "Belém do Piauí", "Queimada Nova",
        "Marcolândia", "Caldeirão Grande do Piauí", "Caridade do Piauí", "Curral Novo do Piauí",
        "Massapê do Piauí", "Padre Marcos", "São Luís do Piauí", "Bocaina",
        "Aroeiras do Itaim", "Arraial", "Campinas do Piauí", "Inhuma",
        "Sussuapara", "Baixa Grande do Ribeiro", "Santa Luz", "Ribeiro Gonçalves",
        "Bom Jesus", "Uruçuí", "Currais", "Palmeira do Piauí",
        "Cristino Castro", "Gilbués", "Monte Alegre do Piauí", "Redenção do Gurguéia",
        "Curimatá", "Avelino Lopes", "Morro Cabeça no Tempo", "Guaribas",
        "Brejo do Piauí", "São Gonçalo do Gurguéia", "Corrente", "Parnaguá",
        "Júlio Borges", "Cristalândia do Piauí", "Santa Rosa do Piauí", "Alvorada do Gurguéia",
        "Barreiras do Piauí", "São Braz do Piauí", "Canto do Buriti", "Anísio de Abreu",
        "Caracol", "Fartura do Piauí", "São Francisco de Assis do Piauí", "Bonfim do Piauí",
        "Jurema", "Pavussu", "Itaueira", "Bertolínia",
        "Marcos Parente", "Canavieira", "Nazaré do Piauí", "Regeneração",
        "Jerumenha", "Angical do Piauí", "Arraial", "Hugo Napoleão",
        "São Pedro do Piauí", "Beneditinos", "Coivaras", "Lagoa Alegre",
        "Miguel Leão", "Monsenhor Gil", "Campo Largo do Piauí", "São João da Serra",
        "Capitão de Campos", "Lagoa de São Francisco", "Nossa Senhora de Nazaré", "Alto Longá",
        "Cabeceiras do Piauí", "Cocal", "Cocal dos Alves", "Buriti dos Lopes",
        "Luís Correia", "Cajueiro da Praia", "Ilha Grande", "Parnaíba",
        "Murici dos Portelas", "Madeiro", "Matias Olímpio", "Porto",
        "Luzilândia", "Joaquim Pires", "Morro do Chapéu do Piauí", "Bom Princípio do Piauí",
        "Brasileira", "Piracuruca", "Piripiri", "Milton Brandão",
        "São João do Arraial", "Domingos Mourão", "Pedro II", "Bom Jesus do Piauí",
        "Juazeiro do Piauí", "Paquetá", "São Luís do Piauí", "Floresta do Piauí",
        "Geminiano", "Ipiranga do Piauí", "Lagoa do Sítio", "Francisco Ayres",
        "Novo Oriente do Piauí", "São Francisco do Piauí", "Barra d'Alcântara", "Batalha",
        "Água Branca", "Buriti dos Montes", "Capitão Gervásio Oliveira", "São Miguel do Tapuio",
        "Campo Maior", "Castelo do Piauí", "Juazeiro do Piauí", "Novo Santo Antônio",
    ],
    "Rio de Janeiro": [
        "Rio de Janeiro", "São Gonçalo", "Duque de Caxias", "Nova Iguaçu",
        "Niterói", "Belford Roxo", "São João de Meriti", "Campos dos Goytacazes",
        "Petrópolis", "Volta Redonda", "Magé", "Itaboraí",
        "Macaé", "Mesquita", "Nova Friburgo", "Barra Mansa",
        "Nilópolis", "Teresópolis", "Angra dos Reis", "Queimados",
        "São Francisco de Itabapoana", "Cabo Frio", "Armação dos Búzios", "Arraial do Cabo",
        "Casimiro de Abreu", "Rio das Ostras", "Macaé", "Carapebus",
        "Quissamã", "Campos dos Goytacazes", "São Fidélis", "Cardoso Moreira",
        "São João da Barra", "Italva", "Cambuci", "Miracema",
        "Laje do Muriaé", "Itaperuna", "Natividade", "Porciúncula",
        "Varre-Sai", "Bom Jesus do Itabapoana", "Aperibé", "Santo Antônio de Pádua",
        "Itaocara", "Cantagalo", "Cordeiro", "Macuco",
        "Santa Maria Madalena", "São Sebastião do Alto", "Trajano de Moraes", "Nova Friburgo",
        "Bom Jardim", "Duas Barras", "Carmo", "Sapucaia",
        "Três Rios", "Paraíba do Sul", "Areal", "Comendador Levy Gasparian",
        "Vassouras", "Miguel Pereira", "Paty do Alferes", "Mendes",
        "Engenheiro Paulo de Frontin", "Paracambi", "Japeri", "Seropédica",
        "Itaguaí", "Mangaratiba", "Angra dos Reis", "Paraty",
        "Rio Claro", "Barra do Piraí", "Valença", "Rio das Flores",
        "Volta Redonda", "Pinheiral", "Piraí", "Barra Mansa",
        "Resende", "Itatiaia", "Porto Real", "Quatis",
        "Rio de Janeiro", "Guapimirim", "Cachoeiras de Macacu", "Silva Jardim",
        "Araruama", "Saquarema", "Maricá", "São Pedro da Aldeia",
        "Iguaba Grande", "Cabo Frio", "Búzios", "Arraial do Cabo",
        "Rio Bonito", "Tanguá", "Itaboraí", "Niterói",
    ],
    "Rio Grande do Norte": [
        "Natal", "Mossoró", "Parnamirim", "São Gonçalo do Amarante",
        "Ceará-Mirim", "Caicó", "Açu", "Macaíba",
        "Currais Novos", "Santa Cruz", "Nova Cruz", "São José de Mipibu",
        "Pau dos Ferros", "Apodi", "João Câmara", "Touros",
        "Extremoz", "Areia Branca", "Jardim de Piranhas", "São Paulo do Potengi",
        "Goianinha", "Tibau do Sul", "Nísia Floresta", "Monte Alegre",
        "Ielmo Marinho", "Poço Branco", "Bom Jesus", "Pureza",
        "Taipu", "São Miguel de Touros", "Pedro Velho", "Canguaretama",
        "Espírito Santo", "Baía Formosa", "Vila Flor", "Montanhas",
        "São José do Campestre", "Lagoa de Pedras", "Lagoa Salgada", "Santo Antônio",
        "Vera Cruz", "Brejinho", "Pedro Avelino", "Lajes",
        "Angicos", "Fernando Pedroza", "Afonso Bezerra", "Ipanguaçu",
        "Jucurutu", "Itajá", "Triunfo Potiguar", "Carnaubais",
        "Porto do Mangue", "Pendências", "Mossoró", "Grossos",
        "Tibau", "Serra do Mel", "Upanema", "Patu",
        "Rodolfo Fernandes", "Severiano Melo", "Doutor Severiano", "Major Sales",
        "São Miguel", "Encanto", "Pau dos Ferros", "Luís Gomes",
        "Pilões", "José da Penha", "Venha-Ver", "Coronel João Pessoa",
        "Riacho de Santana", "São Francisco do Oeste", "Tenente Ananias", "Alexandria",
        "Portalegre", "Antônio Martins", "Frutuoso Gomes", "Martins",
        "Olho-d'Água do Borges", "Pêssego", "Caraúbas", "Tabuleiro Grande",
        "Augusto Severo", "Paraú", "Itaú", "Umarizal",
        "Viçosa", "Serrinha dos Pintos", "Marcelino Vieira", "Rafael Fernandes",
        "Riacho de Santana", "Jardim de Angicos", "Cachoeira dos Índios", "Lagoa Nova",
        "Cerro Corá", "Florânia", "São Vicente", "Santana do Seridó",
        "Serra Negra do Norte", "Timbaúba dos Batistas", "Caicó", "Jardim de Piranhas",
        "São João do Sabugi", "Cruzeta", "Acari", "Carnaúba dos Dantas",
        "Currais Novos", "Equador", "Parelhas", "Ouro Branco",
        "Campo Redondo", "Jaçanã", "Jucurutu", "Bodó",
        "Tenente Laurentino Cruz", "São Tomé", "Ruy Barbosa", "Coronel Ezequiel",
        "Sítio Novo", "Bento Fernandes", "Pedra Preta", "São Bento do Norte",
        "Caiçara do Norte", "Galinhos", "Guamaré", "Macau",
        "Pedra Grande", "São Miguel do Gostoso", "Touros", "Rio do Fogo",
    ],
    "Rio Grande do Sul": [
        "Porto Alegre", "Caxias do Sul", "Pelotas", "Canoas",
        "Santa Maria", "Gravataí", "Viamão", "Novo Hamburgo",
        "São Leopoldo", "Rio Grande", "Alvorada", "Passo Fundo",
        "Sapucaia do Sul", "Uruguaiana", "Santa Cruz do Sul", "Cachoeirinha",
        "Bagé", "Bento Gonçalves", "Erechim", "Guaíba",
        "Cachoeira do Sul", "Santana do Livramento", "Esteio", "Ijuí",
        "Alegrete", "Lajeado", "São Gabriel", "Cruz Alta",
        "Sapiranga", "Santo Ângelo", "Farroupilha", "Novo Hamburgo",
        "Frederico Westphalen", "Vacaria", "Camaquã", "Encantado",
        "Garibaldi", "Bom Jesus", "Três Passos", "Santiago",
        "Palmeira das Missões", "Carazinho", "Sarandi", "Não-Me-Toque",
        "Marau", "Getúlio Vargas", "Sananduva", "Tapejara",
        "Soledade", "Espumoso", "Ibirubá", "Júlio de Castilhos",
        "Tupanciretã", "São Borja", "Itaqui", "Quaraí",
        "Rosário do Sul", "Dom Pedrito", "Lavras do Sul", "Caçapava do Sul",
        "São Sepé", "Vila Nova do Sul", "São Gabriel", "Hulha Negra",
        "Aceguá", "Candiota", "Pedras Altas", "Pinheiro Machado",
        "Piratini", "Canguçu", "Arroio Grande", "Herval",
        "Jaguarão", "Pelotas", "Capão do Leão", "Morro Redondo",
        "Turuçu", "São Lourenço do Sul", "Tavares", "São José do Norte",
        "Rio Grande", "Santa Vitória do Palmar", "Chuí", "Arroio do Sal",
        "Torres", "Três Cachoeiras", "Morrinhos do Sul", "Dom Pedro de Alcântara",
        "Três Forquilhas", "Terra de Areia", "Capão da Canoa", "Xangri-lá",
        "Imbé", "Tramandaí", "Osório", "Maquiné",
        "Itati", "Barra do Ouro", "Rolante", "Riozinho",
        "São Francisco de Paula", "Cambará do Sul", "Jaquirana", "Canela",
        "Gramado", "Nova Petrópolis", "Picada Café", "Linha Nova",
        "Feliz", "São Vendelino", "Carlos Barbosa", "Garibaldi",
        "Bento Gonçalves", "Veranópolis", "Nova Prata", "Guaporé",
        "Serafina Corrêa", "Casca", "Paraí", "Nova Bassano",
        "Cotiporã", "Fagundes Varela", "Vista Alegre do Prata", "Protásio Alves",
        "Flores da Cunha", "Antônio Prado", "Ipê", "Lagoa Vermelha",
        "Muitos Capões", "Esmeralda", "Pinhal da Serra", "Vacaria",
        "Monte Alegre dos Campos", "São José dos Ausentes", "Cambará do Sul",
        "Campestre da Serra", "São Marcos", "Fontoura Xavier", "Erebango",
        "Gaurama", "Barão de Cotegipe", "Erechim", "Erval Grande",
        "Áurea", "Aratiba", "Severiano de Almeida", "Viadutos",
        "Marcelino Ramos", "Maximiliano de Almeida", "Cacique Doble", "Ibiaçá",
        "Passo Fundo", "Mato Castelhano", "Pontão", "Coxilha",
        "Carazinho", "Almirante Tamandaré do Sul", "Boa Vista do Cadeado", "Quinze de Novembro",
        "Selbach", "Tapera", "Ibirubá", "Boa Vista do Incra",
        "Fortaleza dos Valos", "Campos Borges", "Salto do Jacuí", "Colorado",
        "Arroio do Tigre", "Tunas", "Sobradinho", "Lagoão",
        "Passa Sete", "Santa Cruz do Sul", "Venâncio Aires", "Candelária",
        "Rio Pardo", "General Câmara", "Triunfo", "Montenegro",
        "São Jerônimo", "Butiá", "Charqueadas", "Eldorado do Sul",
        "Glorinha", "Taquara", "Parobé", "Igrejinha",
        "Três Coroas", "Nova Hartz", "Araricá", "Campo Bom",
        "Estância Velha", "Dois Irmãos", "Ivoti", "Portão",
        "São Sebastião do Caí", "Harmonia", "Brochier", "Afonso Lourenço",
        "Montenegro", "Triunfo", "Taquari", "Bom Retiro do Sul",
        "Colinas", "Imigrante", "Westfália", "Marques de Souza",
        "Lajeado", "Arroio do Meio", "Cruzeiro do Sul", "Capitão",
        "Poço das Antas", "Nova Bréscia", "Canudos do Vale", "Roca Sales",
        "Muçum", "Vespasiano Corrêa", "Dois Lajeados", "Putinga",
        "Ilópolis", "Anta Gorda", "Encantado", "Relvado",
        "Doutor Ricardo", "Travesseiro", "Sério", "Arroio do Meio",
        "Estrela", "Teutônia", "Paverama", "Tabaí",
        "Bom Princípio", "Pareci Novo", "Alto Feliz", "Vale Real",
        "Linha Nova", "Tupandi", "Barão", "Presidente Lucena",
        "Morro Reuter", "Dois Irmãos", "Santa Maria do Herval", "Novo Hamburgo",
        "Campo Bom", "Sapiranga", "Parobé", "Taquara",
        "Rolante", "Riozinho", "Três Coroas", "Igrejinha",
        "Gramado", "Canela", "São Francisco de Paula", "Jaquirana",
        "Cambará do Sul", "Bom Jesus", "Esmeralda", "Vacaria",
        "Lagoa Vermelha", "Ibiaçá", "Cacique Doble", "Maximiliano de Almeida",
        "Sananduva", "Tapejara", "Getúlio Vargas", "Erebango",
        "Gaurama", "Barão de Cotegipe", "Aratiba", "Áurea",
        "Severiano de Almeida", "Viadutos", "Marcelino Ramos", "Três Arroios",
        "Barra do Rio Azul", "Between", "Entre Rios do Sul", "Erval Grande",
        "Itatiba do Sul", "Faxinalzinho", "Novo Tiradentes", "Gramado dos Loureiros",
        "Cristal do Sul", "Pinheirinho do Vale", "Novo Barreiro", "Palmitinho",
        "Esperança do Sul", "Vista Alegre", "Seberi", "Erval Seco",
        "Três Passos", "Bom Progresso", "Redentora", "Miraguaí",
        "Tenente Portela", "Derrubadas", "São Pedro do Butiá", "Alecrim",
        "Tucunduva", "Senador Salgado Filho", "Cândido Godói", "Porto Lucena",
        "Porto Xavier", "Roque Gonzales", "São Nicolau", "São Paulo das Missões",
        "Dezesseis de Novembro", "Garruchos", "São Luiz Gonzaga", "Santo Ângelo",
        "Giruá", "Vitória das Missões", "Bossoroca", "Entre-Ijuís",
        "Eugênio de Castro", "Pirapó", "São Miguel das Missões", "Rosario do Sul",
        "Ijuí", "Panambi", "Pejuçara", "Augusto Pestana",
        "Ajuricaba", "Chiapeta", "Bozano", "Catuípe",
        "Coronel Barros", "Inhacorá", "São Martinho", "Boa Vista do Cadeado",
        "Jóia", "Senador Salgado Filho", "Independência", "Braga",
        "Novo Machado", "Horizontina", "Santa Rosa", "Cândido Godói",
        "Tuparendi", "Santo Cristo", "São José do Inhacorá", "Campina das Missões",
        "Guarani das Missões", "Sete de Setembro", "Rolador", "Crissiumal",
        "Humaitá", "Tiradentes do Sul", "Sede Nova", "Bom Progresso",
        "Campo Novo", "Boa Vista do Buricá", "Porto Mauá", "Alecrim",
        "Três de Maio", "São Paulo das Missões", "Cerro Largo", "Salvador das Missões",
        "Mato Queimado", "São Pedro do Butiá", "Ubiretama", "Roque Gonzales",
        "Alegria", "Augusto Pestana", "Panambi", "Cruz Alta",
        "Quinze de Novembro", "Salto do Jacuí", "Ibirubá", "Não-Me-Toque",
        "Tapera", "Selbach", "Espumoso", "Campos Borges",
        "Fortaleza dos Valos", "Boa Vista do Incra", "Lagoa dos Três Cantos", "Saldanha Marinho",
        "Mormaço", "Nicolau Vergueiro", "Tio Hugo", "Vítor Graeff",
        "Alto Alegre", "Boa Vista do Incra", "Ernestina", "Coxilha",
        "Mato Castelhano", "Pontão", "Passo Fundo", "Marau",
        "Ciríaco", "Ibiaçá", "Casca", "Muitos Capões",
        "Lagoa Vermelha", "Ipê", "Vacaria", "Bom Jesus",
        "Esmeralda", "Pinhal da Serra", "São José dos Ausentes", "Jaquirana",
        "Cambará do Sul", "São Francisco de Paula", "Canela", "Gramado",
        "Três Coroas", "Igrejinha", "Taquara", "Parobé",
        "Rolante", "Riozinho", "Nova Hartz", "Araricá",
        "Campo Bom", "Estância Velha", "Dois Irmãos", "Ivoti",
        "Portão", "São Sebastião do Caí", "Montenegro", "Taquari",
        "Bom Retiro do Sul", "Colinas", "Imigrante", "Westfália",
        "Lajeado", "Estrela", "Teutônia", "Paverama",
        "Arroio do Meio", "Encantado", "Roca Sales", "Muçum",
        "Dois Lajeados", "Putinga", "Ilópolis", "Anta Gorda",
        "Guaporé", "Serafina Corrêa", "Casca", "Nova Prata",
        "Veranópolis", "Bento Gonçalves", "Garibaldi", "Carlos Barbosa",
        "São Vendelino", "Feliz", "Linha Nova", "Picada Café",
        "Nova Petrópolis", "Gramado", "Canela", "Caxias do Sul",
    ],
    "Rondônia": [
        "Porto Velho", "Ji-Paraná", "Ariquemes", "Vilhena",
        "Cacoal", "Rolim de Moura", "Guajará-Mirim", "Jaru",
        "Ouro Preto do Oeste", "Espigão d'Oeste", "Pimenta Bueno", "Colorado do Oeste",
        "Cerejeiras", "Corumbiara", "Chupinguaia", "Parecis",
        "Pimenteiras do Oeste", "Novo Horizonte do Oeste", "Alta Floresta d'Oeste", "São Francisco do Guaporé",
        "São Miguel do Guaporé", "Seringueiras", "Nova Brasilândia d'Oeste", "Urupá",
        "Mirante da Serra", "Vale do Paraíso", "Presidente Médici", "Ministro Andreazza",
        "Castanheiras", "Cabixi", "Vilhena", "Primavera de Rondônia",
        "Santa Luzia d'Oeste", "Alto Alegre dos Parecis", "Cujubim", "Rio Crespo",
        "Campo Novo de Rondônia", "Monte Negro", "Buritis", "Cacaulândia",
        "Itapuã do Oeste", "Candeias do Jamari", "Porto Velho", "Governador Jorge Teixeira",
        "Machadinho d'Oeste", "Alvorada d'Oeste", "São Felipe d'Oeste", "Rolim de Moura",
        "Alta Floresta d'Oeste", "Novo Horizonte do Oeste", "Vale do Anari", "Theobroma",
    ],
    "Roraima": [
        "Boa Vista", "Caracaraí", "Rorainópolis", "Mucajaí",
        "Alto Alegre", "Pacaraima", "Normandia", "Bonfim",
        "Cantá", "Iracema", "Caroebe", "São João da Baliza",
        "São Luiz do Anauá", "Uiramutã", "Amajari", "Alto Alegre",
    ],
    "Santa Catarina": [
        "Joinville", "Florianópolis", "Blumenau", "São José", "Itajaí",
        "Chapecó", "Palhoça", "Criciúma", "Jaraguá do Sul", "Lages",
        "Brusque", "Balneário Camboriú", "Camboriú", "Tubarão", "Navegantes",
        "Concórdia", "Rio do Sul", "Indaial", "São Bento do Sul", "Araranguá",
        "Gaspar", "Biguaçu", "Itapema", "Mafra", "Caçador", "Canoinhas",
        "Içara", "Videira", "São Miguel do Oeste", "Xanxerê", "Curitibanos",
        "Braço do Norte", "Fraiburgo", "Porto União", "Campos Novos",
        "Capivari de Baixo", "Garopaba", "Guaramirim", "Ituporanga", "Laguna",
        "Tijucas", "Pomerode", "Joaçaba", "Sombrio", "Forquilhinha", "Imbituba",
        "Xaxim", "Balneário Piçarras", "São João Batista", "Maravilha",
        "Três Barras", "Santo Amaro da Imperatriz", "Urussanga", "Penha",
        "Schroeder", "Cocal do Sul", "São Ludgero", "Taió", "Seara",
        "Guabiruba", "Jaguaruna", "Treze Tílias", "Rodeio", "Massaranduba",
        "Antônio Carlos", "Rio Negrinho", "Ascurra", "Balneário Arroio do Silva",
        "Benedito Novo", "Coronel Freitas", "Itá", "Mondaí", "Nova Trento",
        "Orleans", "Otacílio Costa", "Papanduva", "Piratuba", "Porto Belo",
        "Presidente Getúlio", "Quilombo", "Salete", "Santa Cecília",
        "Santa Terezinha", "São Carlos", "São Domingos", "São José do Cedro",
        "São Lourenço do Oeste", "São Martinho", "Saudades", "Tangará",
        "Timbé do Sul", "Treviso", "Agronômica", "Água Doce", "Águas Frias",
        "Águas Mornas", "Águas de Chapecó", "Alfredo Wagner", "Alto Bela Vista",
        "Anchieta", "Angelina", "Anitápolis", "Arabutã", "Araquari", "Armazém",
        "Arroio Trinta", "Balneário Barra do Sul", "Balneário Gaivota",
        "Barra Bonita", "Barra Velha", "Bela Vista do Toldo", "Belmonte",
        "Bocaina do Sul", "Bom Jardim da Serra", "Bom Jesus", "Bom Jesus do Oeste",
        "Bom Retiro", "Bombinhas", "Botuverá", "Braço do Trombudo", "Brunópolis",
        "Caibi", "Calmon", "Campo Alegre", "Campo Belo do Sul", "Campo Erê",
        "Canelinha", "Capão Alto", "Capinzal", "Catanduvas", "Caxambu do Sul",
        "Cerro Negro", "Chapadão do Lageado", "Cordilheira Alta", "Coronel Martins",
        "Correia Pinto", "Cunha Porã", "Cunhataí", "Descanso", "Dionísio Cerqueira",
        "Dona Emma", "Doutor Pedrinho", "Entre Rios", "Ermo", "Erval Velho",
        "Faxinal dos Guedes", "Flor do Sertão", "Formosa do Sul", "Frei Rogério",
        "Galvão", "Grão Pará", "Gravatal", "Guaraciaba", "Guarujá do Sul",
        "Herval d'Oeste", "Ibiam", "Ibicaré", "Iomerê", "Ipira", "Iporã do Oeste",
        "Ipuaçu", "Iraceminha", "Irani", "Irati", "Irineópolis", "Itaiópolis",
        "Itapiranga", "Itapoá", "Jaborá", "Jacinto Machado", "Jardinópolis",
        "Jupiá", "Lacerdópolis", "Lajeado Grande", "Lebon Régis", "Leoberto Leal",
        "Luzerna", "Macieira", "Major Gercino", "Major Vieira", "Marema",
        "Matos Costa", "Meleiro", "Mirim Doce", "Modelo", "Morro Grande",
        "Morro da Fumaça", "Nova Erechim", "Nova Itaberaba", "Nova Veneza",
        "Novo Horizonte", "Ouro", "Ouro Verde", "Paial", "Painel", "Palmitos",
        "Paraíso", "Passo de Torres", "Pedras Grandes", "Peritiba", "Petrolândia",
        "Pinhalzinho", "Pinheiro Preto", "Ponte Alta", "Ponte Alta do Norte",
        "Ponte Serrada", "Presidente Castello Branco", "Presidente Nereu",
        "Princesa", "Rancho Queimado", "Rio das Antas", "Rio Fortuna", "Rio Rufino",
        "Riqueza", "Romelândia", "Saltinho", "Salto Veloso", "Sangão",
        "Santa Helena", "Santa Rosa do Sul", "Santa Terezinha do Progresso",
        "Santiago do Sul", "São Bernardino", "São Bonifácio", "São Cristóvão do Sul",
        "São Francisco do Sul", "São João do Itaperiú", "São João do Oeste",
        "São Joaquim", "São Miguel da Boa Vista", "São Pedro de Alcântara",
        "Serra Alta", "Sul Brasil", "Tigrinhos", "Timbó", "Timbó Grande",
        "Treze de Maio", "Trombudo Central", "Tunápolis", "Turvo", "União do Oeste",
        "Urubici", "Urupema", "Vargeão", "Vargem", "Vargem Bonita", "Vidal Ramos",
        "Vitor Meireles", "Witmarsum", "Xavantina", "Zortéa",
    ],
    "São Paulo": [
        "São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo",
        "Santo André", "São José dos Campos", "Ribeirão Preto", "Osasco",
        "Sorocaba", "Mauá", "São José do Rio Preto", "Mogi das Cruzes",
        "Santos", "Diadema", "Jundiaí", "Piracicaba",
        "Carapicuíba", "Bauru", "Itaquaquecetuba", "São Vicente",
        "Franca", "Guarujá", "Taubaté", "Praia Grande",
        "Limeira", "Suzano", "Taboão da Serra", "Sumaré",
        "Barueri", "Embu das Artes", "São Carlos", "Indaiatuba",
        "Cotia", "Americana", "Marília", "Araraquara",
        "Jacareí", "Hortolândia", "Presidente Prudente", "Rio Claro",
        "Araçatuba", "Santa Bárbara d'Oeste", "Ferraz de Vasconcelos", "São Caetano do Sul",
        "Itapevi", "Itu", "Botucatu", "São João da Boa Vista",
        "Ribeirão Pires", "Guaratinguetá", "Birigui", "Itapecerica da Serra",
        "São Roque", "Atibaia", "Catanduva", "Pindamonhangaba",
        "Bragança Paulista", "Jaú", "Itapetininga", "Caçapava",
        "Ourinhos", "Lins", "Barretos", "Bebedouro",
        "Sertãozinho", "Olímpia", "Fernandópolis", "Votuporanga",
        "Mirassol", "Araras", "Leme", "Pirassununga",
        "Cosmópolis", "Nova Odessa", "Monte Mor", "Paulínia",
        "Valinhos", "Vinhedo", "Itatiba", "Campo Limpo Paulista",
        "Várzea Paulista", "Jarinu", "Pedreira", "Amparo",
        "Lindóia", "Monte Alegre do Sul", "Pinhalzinho", "Morungaba",
        "Tuiuti", "Águas de Lindóia", "Serra Negra", "Socorro",
        "Jaguariúna", "Santo Antônio de Posse", "Holambra", "Artur Nogueira",
        "Engenheiro Coelho", "Conchal", "Itapira", "Mogi Guaçu",
        "Mogi Mirim", "Estiva Gerbi", "São Sebastião", "Caraguatatuba",
        "Ubatuba", "Ilhabela", "Bertioga", "Mongaguá",
        "Itanhaém", "Peruíbe", "Registro", "Iguape",
        "Ilha Comprida", "Cananéia", "Miracatu", "Juquiá",
        "Eldorado", "Iporanga", "Apiaí", "Capão Bonito",
        "Guapiara", "Ribeira", "Itaberá", "Itararé",
        "Buri", "Taquarivaí", "Nova Campina", "Coronel Macedo",
        "Piraju", "Tejupá", "São Pedro do Turvo", "Cândido Mota",
        "Assis", "Palmital", "Paraguaçu Paulista", "Quatá",
        "Iepê", "Maracaí", "Tarumã", "Campos Novos Paulista",
        "Pedrinhas Paulista", "Cruzália", "Florínea", "Ibirarema",
        "Borá", "Echaporã", "Lutécia", "Quintana",
        "Gália", "Garça", "Vera Cruz", "Tupã",
        "Queiroz", "Pompéia", "Rinópolis", "Osvaldo Cruz",
        "Parapuã", "Lucélia", "Adamantina", "Flórida Paulista",
        "Inúbia Paulista", "Pracinha", "Sagres", "Irapuru",
        "Junqueirópolis", "Dracena", "Monte Castelo", "Tupi Paulista",
        "Nova Guataporanga", "Panorama", "Santa Mercedes", "Ouro Verde",
        "Presidente Venceslau", "Piquerobi", "Santo Anastácio", "Mirante do Paranapanema",
        "Sandovalina", "Caiabú", "Nantes", "Marabá Paulista",
        "Teodoro Sampaio", "Euclides da Cunha Paulista", "Rosana", "Primavera",
        "Narandiba", "Tarabai", "Álvares Machado", "Presidente Epitácio",
        "Presidente Bernardes", "Regente Feijó", "Martinópolis", "Ribeirão dos Índios",
        "Indiana", "Alfredo Marcondes", "Caiabu", "Rancharia",
        "Herculândia", "Iacri", "Bastos", "Arealva",
        "Piratininga", "Agudos", "Lençóis Paulista", "Borebi",
        "Pederneiras", "Bocaina", "Dois Córregos", "Mineiros do Tietê",
        "Barra Bonita", "Igaraçu do Tietê", "Boa Esperança do Sul", "Gavião Peixoto",
        "Ibitinga", "Itápolis", "Borborema", "Tabatinga",
        "Américo Brasiliense", "Santa Lúcia", "Rincão", "Descalvado",
        "Porto Ferreira", "Santa Cruz das Palmeiras", "Tambaú", "Casa Branca",
        "Mococa", "São José do Rio Pardo", "Vargem Grande do Sul", "Águas da Prata",
        "Divinolândia", "São Sebastião da Grama", "Caconde", "Tapiratiba",
        "Itamogi", "Itobi", "Santo Antônio do Jardim", "Espírito Santo do Pinhal",
        "São Bento do Sapucaí", "Campos do Jordão", "Santo Antônio do Pinhal", "Monteiro Lobato",
        "Paraibuna", "Natividade da Serra", "Redenção da Serra", "Lagoinha",
        "Cunha", "São Luís do Paraitinga", "Jambeiro", "Salesópolis",
        "Biritiba-Mirim", "Guararema", "Santa Branca", "Roseira",
        "Aparecida", "Lorena", "Canas", "Cruzeiro",
        "Lavrinhas", "Silveiras", "São José do Barreiro", "Arapeí",
        "Areias", "Queluz", "Bananal", "Aguaí",
        "Nazaré Paulista", "Piracaia", "Vargem", "Bom Jesus dos Perdões",
        "Igaratá", "Santa Isabel", "Arujá", "Poá",
        "Santa Branca", "Guararema", "Biritiba-Mirim", "Salesópolis",
        "Suzano", "Mogi das Cruzes", "Itaquaquecetuba", "Ferraz de Vasconcelos",
        "Poá", "Arujá", "Santa Isabel", "Guararema",
        "Jacareí", "São José dos Campos", "Caçapava", "Taubaté",
        "Tremembé", "Pindamonhangaba", "Roseira", "Aparecida",
        "Guaratinguetá", "Lorena", "Cruzeiro", "Piquete",
        "Cachoeira Paulista", "Canas", "Lavrinhas", "Silveiras",
        "São José do Barreiro", "Arapeí", "Areias", "Queluz",
        "Bananal", "Angra dos Reis", "Paraty", "Cunha",
        "São Luís do Paraitinga", "Natividade da Serra", "Lagoinha", "Redenção da Serra",
        "Paraibuna", "Jambeiro", "Monteiro Lobato", "Santo Antônio do Pinhal",
        "Campos do Jordão", "São Bento do Sapucaí", "Espírito Santo do Pinhal", "Águas de Lindóia",
        "Serra Negra", "Socorro", "Amparo", "Pedreira",
        "Jaguariúna", "Holambra", "Artur Nogueira", "Engenheiro Coelho",
        "Cosmópolis", "Paulínia", "Americana", "Nova Odessa",
        "Santa Bárbara d'Oeste", "Sumaré", "Hortolândia", "Monte Mor",
        "Campinas", "Valinhos", "Vinhedo", "Itatiba",
        "Bragança Paulista", "Atibaia", "Jarinu", "Campo Limpo Paulista",
        "Várzea Paulista", "Jundiaí", "Cajamar", "Franco da Rocha",
        "Francisco Morato", "Caieiras", "Mairiporã", "Guarulhos",
        "Arujá", "Santa Isabel", "Igaratá", "Jacareí",
        "Ilha Solteira", "Pereira Barreto", "Andradina", "Castilho",
        "Guaraçaí", "Mirandópolis", "Murutinga do Sul", "Lavínia",
        "Valparaíso", "Nova Independência", "Sud Mennucci", "Buritama",
        "Coroados", "Gabriel Monteiro", "Glicério", "Penápolis",
        "Avanhandava", "Braúna", "Luiziânia", "Santópolis do Aguapeí",
        "Getulina", "Guaimbê", "Guaiçara", "Promissão",
        "Lins", "Sabino", "Pongaí", "Uru",
        "Reginópolis", "Balbinos", "Pirajuí", "Avaré",
        "Cerqueira César", "Arandu", "Iaras", "Manduri",
        "Óleo", "Taguaí", "Itaí", "Paranapanema",
        "Piraju", "Sarutaiá", "Taquarituba", "Barão de Antonina",
        "São Miguel Arcanjo", "Capão Bonito", "Guapiara", "Ribeira",
        "Barra do Chapéu", "Itapirapuã Paulista", "Bom Sucesso de Itararé", "Nova Campina",
        "Itararé", "Itapeva", "Taquarivaí", "Itaberá",
        "Riversul", "Coronel Macedo", "Tejupá", "São Pedro do Turvo",
        "Ourinhos", "Salto Grande", "Chavantes", "Ipaussu",
        "Canitar", "Santa Cruz do Rio Pardo", "Bernardino de Campos", "Espírito Santo do Turvo",
        "Óleo", "Taguaí", "Cândido Mota", "Palmital",
        "Maracaí", "Iepê", "Salto Grande", "Ipaussu",
        "Assis", "Paraguaçu Paulista", "Quatá", "Tarumã",
        "Campos Novos Paulista", "Pedrinhas Paulista", "Cruzália", "Florínea",
        "Ibirarema", "Borá", "Echaporã", "Lutécia",
        "Quintana", "Gália", "Garça", "Vera Cruz",
        "Marília", "Oriente", "Pompéia", "Rinópolis",
        "Osvaldo Cruz", "Parapuã", "Lucélia", "Adamantina",
        "Flórida Paulista", "Pacaembu", "Salmourão", "Tupã",
        "Queiroz", "Herculândia", "Iacri", "Bastos",
        "Rancharia", "Caiabu", "Alfredo Marcondes", "Indiana",
        "Ribeirão dos Índios", "Martinópolis", "Regente Feijó", "Presidente Bernardes",
        "Presidente Epitácio", "Álvares Machado", "Tarabai", "Narandiba",
        "Sandovalina", "Mirante do Paranapanema", "Santo Anastácio", "Piquerobi",
        "Presidente Venceslau", "Ouro Verde", "Santa Mercedes", "Panorama",
        "Nova Guataporanga", "Tupi Paulista", "Monte Castelo", "Dracena",
        "Junqueirópolis", "Irapuru", "Sagres", "Pracinha",
        "Inúbia Paulista", "Flórida Paulista", "Adamantina", "Lucélia",
        "Parapuã", "Osvaldo Cruz", "Rinópolis", "Pompéia",
    ],
    "Sergipe": [
        "Aracaju", "Nossa Senhora do Socorro", "Lagarto", "Itabaiana",
        "São Cristóvão", "Estância", "Tobias Barreto", "Simão Dias",
        "Nossa Senhora da Glória", "Propriá", "Itabaianinha", "Boquim",
        "Poço Verde", "Ribeirópolis", "Moita Bonita", "Areia Branca",
        "Maruim", "Santo Amaro das Brotas", "Rosário do Catete", "General Maynard",
        "Siriri", "Divina Pastora", "Santa Rosa de Lima", "Riachuelo",
        "Laranjeiras", "São Sebastião", "Malhador", "Itabi",
        "Nossa Senhora Aparecida", "Carira", "Pinhão", "Pedra Mole",
        "São Miguel do Aleixo", "Frei Paulo", "Macambira", "São Domingos",
        "Riachão do Dantas", "Salgado", "Pedrinhas", "Arauá",
        "Boquim", "Cristinápolis", "Umbaúba", "Santa Luzia do Itanhy",
        "Indiaroba", "Estância", "Itaporanga d'Ajuda", "São Antônio",
        "Ilha das Flores", "Brejo Grande", "Pacatuba", "Japaratuba",
        "Pirambu", "Carmópolis", "Japoatã", "Amparo de São Francisco",
        "Propriá", "Telha", "Cedro de São João", "São Francisco",
        "Neópolis", "Santana do São Francisco", "Muribeca", "Graccho Cardoso",
        "Aquidabã", "Cumbe", "Feira Nova", "Itabi",
        "Porto da Folha", "Nossa Senhora de Lourdes", "Monte Alegre de Sergipe", "Gararu",
        "Poço Redondo", "Canindé de São Francisco", "Nossa Senhora da Glória", "Feira Nova",
        "São Miguel do Aleixo", "Itabaiana", "Campo do Brito", "Pedra Mole",
        "Lagarto", "Salgado", "Boquim", "Tobias Barreto",
    ],
    "Tocantins": [
        "Palmas", "Araguaína", "Gurupi", "Porto Nacional",
        "Paraíso do Tocantins", "Colinas do Tocantins", "Guaraí", "Tocantinópolis",
        "Miracema do Tocantins", "Araguatins", "Formoso do Araguaia", "Dianópolis",
        "Pedro Afonso", "Arraias", "Natividade", "Combinado",
        "Alvorada", "Conceição do Tocantins", "Taguatinga", "Novo Acordo",
        "Babaçulândia", "Filadélfia", "Carolina", "Wanderlândia",
        "Araguaçu", "Sandolândia", "Cariri do Tocantins", "Crixás do Tocantins",
        "Aliança do Tocantins", "Figueirópolis", "Talismã", "Sucupira",
        "Palmeirópolis", "São Salvador do Tocantins", "Paranã", "Ponte Alta do Bom Jesus",
        "Rio da Conceição", "Aurora do Tocantins", "Lavandeira", "Novo Jardim",
        "Campos Lindos", "Goiatins", "Recursolândia", "Rio Sono",
        "Lagoa do Tocantins", "Santa Tereza do Tocantins", "Novo Acordo", "Lajeado",
        "Palmas", "Porto Nacional", "Brejinho de Nazaré", "Oliveira de Fátima",
        "Monte do Carmo", "Santa Rosa do Tocantins", "Ipueiras", "Silvanópolis",
        "São Félix do Tocantins", "Mateiros", "Lizarda", "Rio da Conceição",
        "Centenário", "Itacajá", "Recursolândia", "Colméia",
        "Arapoema", "Pau d'Arco", "Xambioá", "Ananás",
        "Angico", "Augustinópolis", "Buriti do Tocantins", "Carrasco Bonito",
        "Esperantina", "Itaguatins", "Nazaré", "Palmeiras do Tocantins",
        "Praia Norte", "Sampaio", "Santa Terezinha do Tocantins", "São Bento do Tocantins",
        "São Miguel do Tocantins", "São Sebastião do Tocantins", "Sítio Novo do Tocantins", "Tocantinópolis",
        "Araguatins", "Cachoeirinha", "Axixá do Tocantins", "Araguanã",
        "Muricilândia", "Piraquê", "Riachinho", "Santa Fé do Araguaia",
        "Aragominas", "Araguaína", "Babaçulândia", "Filadélfia",
        "Juarina", "Nova Olinda", "Palmeirante", "Presidente Kennedy",
        "Tupirama", "Tupiratins", "Guaraí", "Couto de Magalhães",
        "Fortaleza do Tabocão", "Miracema do Tocantins", "Miranorte", "Rio dos Bois",
        "Divinópolis do Tocantins", "Lizarda", "Lagoa do Tocantins", "Pium",
        "Cristalândia", "Chapada de Areia", "Marianópolis do Tocantins", "Pugmil",
        "Paraíso do Tocantins", "Caseara", "Araguacema", "Colmeia",
        "Bandeirantes do Tocantins", "Bernardo Sayão", "Brasilândia do Tocantins", "Itaporã do Tocantins",
        "Nova Rosalândia", "Oliveira de Fátima", "Santa Maria do Tocantins", "Tocantínia",
    ],
}